LABEL_MAPPING_ZH = {
    "3VT_zhao": "早孕期三血管（血流）切面",
    "4CH_zhao": "早孕期四腔心（血流）切面",
    "AC_zhao": "早孕期腹部横切面",
    "CNS_zhao": "早孕期经侧脑室横切面",
    "CRL_zhao": "早孕期胎儿正中矢状切面",
    "NT_zhao": "早孕期NT测量切面",
    "QDFB_zhao": "早孕期脐带腹壁入口横切面",
    "SXZ_zhao": "早孕期双上肢切面",
    "SSZ_zhao": "早孕期双下肢切面",
    "3DFace": "3D彩超",
    "3VV": "三血管切面",
    "4CH": "四腔心切面",
    "4CH-H": "四腔心切面（横）",
    "4CH-lightsplot": "四腔心切面心室强光斑",
    "AAV": "主动脉弓切面",
    "ABS": "上牙槽突切面",
    "AC": "腹径测量横切面",
    "Bladder": "腹壁经膀胱横切面",
    "BPD": "双顶径平面",
    "CRL": "正中矢状切面C",
    "CTAR": "四腔心切面-心胸比",
    "Cereb": "小脑平面",
    "Chest-H": "胸腔横切面",
    "Chest-C": "胸腔冠状切面",
    "DDA": "动脉导管切面",
    "Eye": "眶间距平面",
    "FL": "股骨长轴切面",
    "Foot": "足冠状切面",
    "Forearm": "尺挠骨切面",
    "Four": "第四脑室",
    "Gallbladder": "胆囊切面",
    "HL": "肱骨长轴切面",
    "HardPalate": "硬腭切面",
    "Kidney": "双肾横切面",
    "KidneyVessel": "双肾冠状切面",
    "LVOT": "左室流出道切面",
    "Leg": "胫腓骨长轴切面",
    "Lip": "唇部冠状切面",
    "neg": "未知",
    "NT": "正中矢状切面N",
    "PAB": "肺动脉分叉",
    "Palate": "下颌骨切面",
    "Palm": "手指冠状切面",
    "RVOT": "右室流出道切面",
    "SideFace": "颜面部正中矢状切面",
    "SIVCV": "上下腔切面",
    "Spine": "脊柱纵切面",
    "SVSK": "单肾脏矢状面",
    "Three": "第三脑室",
    "VaVp": "侧脑室平面",
}

LABEL_MAPPING_EN = {
    "3VT_zhao": "Early-pregnancy three-vessel flow view",
    "4CH_zhao": "Early-pregnancy four-chamber flow view",
    "AC_zhao": "Early-pregnancy abdominal axial view",
    "CNS_zhao": "Early-pregnancy lateral ventricle view",
    "CRL_zhao": "Early-pregnancy midsagittal fetal view",
    "NT_zhao": "Early-pregnancy NT measurement view",
    "QDFB_zhao": "Early-pregnancy umbilical cord abdominal wall insertion view",
    "SXZ_zhao": "Early-pregnancy bilateral upper-limb view",
    "SSZ_zhao": "Early-pregnancy bilateral lower-limb view",
    "3DFace": "3D color ultrasound",
    "3VV": "Three-vessel view",
    "4CH": "Four-chamber view",
    "4CH-H": "Four-chamber transverse view",
    "4CH-lightsplot": "Four-chamber echogenic focus view",
    "AAV": "Aortic arch view",
    "ABS": "Upper alveolar ridge view",
    "AC": "Abdominal circumference axial view",
    "Bladder": "Abdominal wall via bladder axial view",
    "BPD": "Biparietal diameter plane",
    "CRL": "Midsagittal view C",
    "CTAR": "Four-chamber cardiothoracic ratio view",
    "Cereb": "Cerebellar plane",
    "Chest-H": "Chest axial view",
    "Chest-C": "Chest coronal view",
    "DDA": "Ductus arteriosus view",
    "Eye": "Interorbital distance plane",
    "FL": "Femur long-axis view",
    "Foot": "Foot coronal view",
    "Forearm": "Radius/ulna view",
    "Four": "Fourth ventricle",
    "Gallbladder": "Gallbladder view",
    "HL": "Humerus long-axis view",
    "HardPalate": "Hard palate view",
    "Kidney": "Bilateral kidneys axial view",
    "KidneyVessel": "Bilateral kidneys coronal view",
    "LVOT": "Left ventricular outflow tract view",
    "Leg": "Tibia/fibula long-axis view",
    "Lip": "Lip coronal view",
    "neg": "Unknown",
    "NT": "Midsagittal view N",
    "PAB": "Pulmonary artery bifurcation",
    "Palate": "Mandible view",
    "Palm": "Finger coronal view",
    "RVOT": "Right ventricular outflow tract view",
    "SideFace": "Facial midsagittal view",
    "SIVCV": "Superior/inferior vena cava view",
    "Spine": "Spine longitudinal view",
    "SVSK": "Single kidney sagittal view",
    "Three": "Third ventricle",
    "VaVp": "Lateral ventricle plane",
}

REPORT_PROMPTS_ZH = [
    "请依次查看以上超声图像，每张图片后注明了解剖部位。请结合所有图像整体分析，撰写该次超声检查的 FINDINGS 和 IMPRESSION。",
    "作为一名超声医生，请依次查看以上图像（每张图片后注明解剖部位），并基于全部图像内容，提供 FINDINGS 和 IMPRESSION。",
    "请依次阅读每张图片（已标注解剖部位），结合所有图像内容，总结 FINDINGS 和 IMPRESSION。",
    "请逐一查看以上超声图像（每张图像后附解剖标签），结合所有图像整体分析，撰写 FINDINGS 和 IMPRESSION。",
    "请仔细阅读以上超声图像（图片顺序已标明，且注明了解剖部位），请整体分析后详细描述 FINDINGS 和 IMPRESSION。",
    "请作为超声影像专家，按顺序查看以上图像（每张图片均已注明解剖部位），请综合所有图像进行分析，并撰写 FINDINGS 和 IMPRESSION。",
    "请逐张检查以上超声图像，图片后已标注对应解剖部位，请基于所有图像的整体信息，总结 FINDINGS 和 IMPRESSION。",
    "请查看以上超声图像（每张图片后已注明解剖部位），无需逐图单独描述，请结合所有图像撰写 FINDINGS 和 IMPRESSION。",
    "请系统性分析以上超声图像（图片顺序及解剖标签已注明），请基于所有图像综合提供 FINDINGS 和 IMPRESSION。",
    "请依次查看以上图像（每张图片后注明了解剖部位），并以超声检查报告的标准格式，撰写 FINDINGS 和 IMPRESSION。",
]

REPORT_PROMPTS_EN = [
    "Please review the above ultrasound images in sequence, with the anatomical site noted after each image. Please analyze all images comprehensively and write the FINDINGS and IMPRESSION for this ultrasound examination.",
    "Acting as an ultrasound physician, please review the above images in sequence (with the anatomical site noted after each image), and provide the FINDINGS and IMPRESSION based on the content of all images.",
    "Please review each image in sequence (with anatomical sites annotated), and summarize the FINDINGS and IMPRESSION combining the content of all images.",
    "Please examine the above ultrasound images one by one (with anatomical labels attached after each image), analyze all images comprehensively, and write the FINDINGS and IMPRESSION.",
    "Please carefully review the above ultrasound images (the order of the images is indicated, and anatomical sites are noted), and describe the FINDINGS and IMPRESSION in detail after a comprehensive analysis.",
    "As an ultrasound imaging expert, please review the above images in order (each image is annotated with the anatomical site), comprehensively analyze all images, and write the FINDINGS and IMPRESSION.",
    "Please inspect the above ultrasound images one by one; the corresponding anatomical sites are labeled after the images. Please summarize the FINDINGS and IMPRESSION based on the overall information from all images.",
    "Please review the above ultrasound images (with the anatomical site noted after each image). There is no need to describe each image individually; please write the FINDINGS and IMPRESSION combining all images.",
    "Please systematically analyze the above ultrasound images (image order and anatomical labels are noted), and provide the FINDINGS and IMPRESSION comprehensively based on all images.",
    "Please review the above images in sequence (with the anatomical site noted after each image), and write the FINDINGS and IMPRESSION in the standard format of an ultrasound examination report.",
]

DIAGNOSIS_PROMPTS_ZH = [
    "请查看以上所有超声图像（每张图像均标注了解剖部位），系统性分析胎儿发育情况，并判断是否存在一种或多种异常情况。",
    "请作为超声专家，综合评估以上图像内容，判断胎儿是否存在可能的异常情况。",
    "请逐张查看图像，并结合整体情况，分析胎儿是否存在发育异常或畸形。",
    "请根据超声图像中的解剖切面，对胎儿情况作出专业判断，并指出是否存在一种或多种异常。",
    "请作为经验丰富的超声医生，对以上图像进行全面诊断，并识别潜在的异常类型。",
    "请分析以上超声图像所示内容，判断胎儿是否存在多种异常情况，并列出具体表现。",
    "请系统性分析所有图像，判断胎儿是否存在异常情况，并描述相关表现。",
    "请仔细阅读这些超声图像，综合判断是否存在多种可能的异常或异常征象。",
    "请根据每张图像对应的解剖切面，专业分析是否存在异常情况，并指出相关部位。",
    "请结合所有图像显示的胎儿情况，进行专业判断，并总结可能存在的多种异常情况。",
]

DIAGNOSIS_PROMPTS_EN = [
    "Please review all the ultrasound images above (each annotated with its anatomical site), systematically analyze the fetal development, and determine whether one or more abnormal conditions are present.",
    "Please act as an ultrasound expert to comprehensively evaluate the content of the images above and determine if there are any possible fetal abnormal conditions.",
    "Please review the images one by one and, in combination with the overall situation, analyze whether the fetus has any development-related abnormal conditions or malformations.",
    "Please make a professional judgment on the fetus based on the anatomical planes in the ultrasound images, and point out whether one or more conditions are present.",
    "Please act as an experienced ultrasound doctor to perform a comprehensive diagnosis on the images above and identify potential types of conditions.",
    "Please analyze the content shown in the ultrasound images above, determine if there are multiple abnormal conditions, and list the specific manifestations.",
    "Please systematically analyze all images, determine whether the fetus has any abnormal conditions, and describe the relevant manifestations.",
    "Please carefully review these ultrasound images and make a comprehensive judgment on whether there are multiple possible conditions or abnormal signs.",
    "Please professionally analyze whether there are any abnormal conditions based on the anatomical planes corresponding to each image, and point out the relevant locations.",
    "Please make a professional judgment based on the fetal condition shown in all images and summarize the multiple abnormal conditions that may be present.",
]
